# # -*- coding: utf-8 -*-
# """Семинар 10.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1aLagLCILn27s0Lh-Fs6Es1YRDWmOrQyu
# """

# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns

# df = pd.read_csv('/content/sample_data/california_housing_test.csv')
# df.head()

# """## Задача 63
# 1. Изобразите отношение households к population с помощью точечного графика
# 2. Визуализировать longitude по отношения к median_house_value, используя линейный график
# 3. Представить гистограмму по housing_median_age
# 4. Изобразить гистограмму по median_house_value с оттенком housing_median_age
# """

# plt.figure(figsize=(16, 8))
# sns.scatterplot(data=df, x='households', y='population')
# ;

# # Визуализировать longitude по отношения к median_house_value, используя линейный график
# sns.relplot(data=df, x='longitude', y='median_house_value', kind='line', aspect=2, height=6)
# ;

# sns.lineplot(data=df, x='longitude', y='median_house_value')
# ;

# # Представить гистограмму по housing_median_age
# plt.figure(figsize=(16, 6))
# sns.histplot(data=df, x='housing_median_age', bins=51)

# plt.title('Распределение возраста домов')
# plt.xlabel('Возраст дома')
# plt.ylabel('Количество')
# plt.xticks(range(0, 53))
# plt.yticks(range(0, 200, 10))
# plt.grid()
# ;

# # Изобразить гистограмму по median_house_value с оттенком housing_median_age

# sns.displot(data=df, x='median_house_value', hue='housing_median_age', legend=False, aspect=2)

# """## Задача №65.  Написать EDA для датасета про пингвинов
# Необходимо:
# 1. Использовать 2-3 точечных графика
# 2. Применить доп измерение в точечных графиках, используя аргументы hue, size, stile
# 3. Использовать PairGrid с типом графика на ваш выбор
# 4. Изобразить Heatmap
# 5. Использовать 2-3 гистограммы

# Чтобы подключить датасет с     пингвинами, воспользуйтесь данным скриптом:
# penguins = sns.load_dataset("penguins")
# penguins.head()

# """

# df_2 = sns.load_dataset("penguins")
# df_2.sample()

# sns.scatterplot(data=df_2, x ='bill_length_mm', y='bill_depth_mm', hue='species')
# ;

# sns.scatterplot(data=df_2, x ='bill_length_mm', y='flipper_length_mm', size='sex', hue='species' )
# ;

# plt.figure(figsize=(16,6))
# sns.scatterplot(data=df_2, x ='flipper_length_mm', y='body_mass_g', hue='species', style='island')
# ;

# """Использовать PairGrid с типом графика на ваш выбор"""

# g=sns.PairGrid(df_2[['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']])
# g.map(sns.scatterplot)

# g=sns.PairGrid(df_2)
# g.map_diag(sns.histplot)
# g.map_offdiag(sns.scatterplot)

# g=sns.PairGrid(df_2, hue='species')
# g.map_diag(sns.histplot)
# g.map_lower(sns.scatterplot)
# g.map_upper(sns.kdeplot)

# """Изобразить Heatmap"""

# df_corr = df_2.corr().round(2)
# df_corr

# sns.heatmap(df_corr, annot=True, cmap='coolwarm', linewidths=1)

# """Использовать 2-3 гистограммы"""

# plt.figure(figsize=(16, 6))
# sns.histplot(data=df_2, x='body_mass_g', bins=36)


# plt.title('Распределение пингвинов по массе')
# plt.xlabel('Вес, кг')
# plt.ylabel('Количество')
# plt.xticks(range(2700, 6400, 100), np.arange(2.7, 6.4, 0.1).round(1))
# plt.yticks(range(0, 24))
# plt.grid()
# ;

# sns.histplot(data=df_2, x='flipper_length_mm')
# ;

# """## Задача №67.
# Создать новый столбец в таблице с пингвинами, который будет отвечать за показатель длины клюва пингвина.
# high - длинный(от 42)
# middle - средний(от 35 до 42)
# low - маленький(до 35)
# """

# df_2.loc[df_2['bill_length_mm'] >= 42, 'height_group'] = 'high'
# df_2.loc[(df_2['bill_length_mm'] >= 35) & (df_2['bill_length_mm'] < 42), 'height_group'] = 'middle'
# df_2.loc[df_2['bill_length_mm'] < 35, 'height_group'] = 'low'
# df_2.sample(30)

# """## Задача №69
# Изобразить гистограмму по flipper_length_mm с оттенком height_group. Сделать анализ
# """

# sns.histplot(df_2, x='flipper_length_mm', hue='height_group')