# print(all([True, True, True, True]))
# print(all([True, False, True, True]))
# print(all([False, False, False, False]))
# print()
# print(any([True, True, True, True]))
# print(any([True, False, True, True]))
# print(any([False, False, False, False]))
# print()
# print(all([1, 2, 3, 4]))
# print(all([1, 0, 3, 4]))
# print(all([0, 0, 0, 0]))
# print()
# print(any([1, 2, 3, 4]))
# print(any([1, 0, 3, 4]))
# print(any([0, 0, 0, 0]))
# print()
# print(all(['dfg', 'sdf', 'sdf', 'cvb']))
# print(all(['dfg', '', 'sdf', 'cvb']))
# print(all(['', '', '', '']))
# print()
# print(any(['dfg', 'sdf', 'sdf', 'cvb']))
# print(any(['dfg', '', 'sdf', 'cvb']))
# print(any(['', '', '', '']))
# print()
# print(all([[''], ('',), {''}, ['']]))
# print(all([[''], [], [''], ['']]))
# print(all([{}, {}, {}, []]))
# print()
# print(any([[''], ('',), {''}, ['']]))
# print(any([[''], [], [''], ['']]))
# print(any([{}, {}, {}, []]))
# print()
